FROM amazoncorretto:17-alpine-jdk
MAINTAINER joesharpcs.co.uk
COPY build/libs/timesheet_service-0.0.1-SNAPSHOT.jar timesheet_service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/timesheet_service-0.0.1-SNAPSHOT.jar"]