# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    image: joesharpcs/timesheet_service:latest
    ports:
      - "8082:8080"
    environment:
      DB_URL: jdbc:postgresql://app-db:5432/timesheets
      OAUTH2_URL: http://auth:8080/realms/ratracejoe
    depends_on:
      app-db:
        condition: service_healthy

  app-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: timesheets123
      POSTGRES_DB: timesheets
      POSTGRES_USER: tsuser
      POSTGRES_PASSWORD: ts-password
    healthcheck:
      test: pg_isready -U tsuser -d timesheets
      interval: 10s
      timeout: 3s
      retries: 3

  auth-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: keycloak123
      POSTGRES_DB: auth
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kc-password
    healthcheck:
      test: pg_isready -U keycloak -d auth
      interval: 10s
      timeout: 3s
      retries: 3

  auth:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin-pw
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://auth-db:5432/auth
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kc-password
    depends_on:
      auth-db:
        condition: service_healthy
    volumes:
      - ./auth/realm-export.json:/opt/keycloak/data/import/main-realm.json:ro
