spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/timesheets
    username: tsuser
    password: the-password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ratracejoe
      client:
        registration:
          keycloak:
            client-id: timesheets-service
            client-secret: rX0uyWb89PxdeclkQoLMtmRtCLRxFlKy
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/ratracejoe
            user-name-attribute: preferred_username
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

cors:
  origin: http://localhost:5173/

logging:
  level:
    org:
      springframework:
        security: DEBUG