spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/timesheets}
    username: tsuser
    password: ts-password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_URL:http://localhost:8080/realms/ratracejoe}
      client:
        registration:
          keycloak:
            client-id: timesheets-service
            client-secret: rX0uyWb89PxdeclkQoLMtmRtCLRxFlKy
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_URL:http://localhost:8080/realms/ratracejoe}
            user-name-attribute: preferred_username
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    org:
      springframework:
        security: DEBUG