spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/timesheets
    username: tsuser
    password: the-password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ratracejoe
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

cors:
  origin: http://localhost:5173/